### ISSUE TITLE
Update Readme's overall look

### ISSUE THREAD

**Issue by Johnkayode** [Johnkayode/Dominos-bot#3]

**Comment by omeiirr** [comment]
Can you elaborate what improvements do you need?

**Comment by Johnkayode** [comment]
There is really nothing much to do. If you find any to add you can

**Comment by omeiirr** [comment]
Okay I can work on this

Can you explain what is meant by [this](https://github.com/Johnkayode/Dominos-bot/blob/master/README.md?plain=1#L26) line:
> Edit the webhook url in the bot.py file and run the bot

This is the relevant section in bot.py:
```python
 updater.start_webhook(listen="0.0.0.0",
                          port=int(PORT),
                          url_path=os.getenv("TELEGRAM_BOT_TOKEN"),
                          webhook_url='https://dominos-order-bot.herokuapp.com/' + os.getenv("TELEGRAM_BOT_TOKEN")
                        )
```

**Comment by Johnkayode** [comment]
You can either replace that with your heroku app url before deploying or comment it out and use
`updater.start_polling()`
to run it locally on your machine.
Although the bot is already live.

**Comment by omeiirr** [comment]
Created a PR [here](https://github.com/Johnkayode/Dominos-bot/pull/4)
Let me know if any changes are required
